### ISSUE TITLE
Can not generate triangles

### ISSUE THREAD

**Issue by blackball** [fogleman/sdf#1]
OS: Debian 10
Python 3.7.3

```python3 example.py``` 

min -0.84543, -0.84543, -0.84543
max 0.845431, 0.845431, 0.845431
step 0.0104847, 0.0104847, 0.0104847
4492125 samples in 64 batches with 8 workers
0 triangles in 0.741009 seconds

**Comment by fogleman** [comment]
Try printing any exceptions that occur here: https://github.com/fogleman/sdf/blob/main/sdf/mesh.py#L33

**Comment by blackball** [comment]
I found the issue. The version of my scikit-image package is too low. It's working now after I upgraded it. 

This project is very inspiring  to me. Thanks!
