### ISSUE TITLE
meshio

### ISSUE THREAD

**Issue by nschloe** [fogleman/sdf#11]
With [meshio](https://github.com/nschloe/meshio) you'd instantly get a plethora of file formats to write to. Probably with a good match.

**Comment by fogleman** [comment]
This looks great, I'll give it a try. Thanks for the suggestion!

**Comment by fogleman** [comment]
Done: https://github.com/fogleman/sdf/commit/609c4f104f2627a3232f28bdefb08e3d7353d883

**Comment by nschloe** [comment]
You could also use meshio for STL writing, but lets consider this done.

**Comment by fogleman** [comment]
Yes, but my implementation is significantly faster, so I kept it.

Also, might I recommend a table of `file extensions => file type` in your readme? That would be helpful.

**Comment by nschloe** [comment]
> Yes, but my implementation is significantly faster, so I kept it.

Perhaps I can improve meshio. I'll back when I get something.

> Also, might I recommend a table of file extensions => file type in your readme? That would be helpful.

Done.

**Comment by nschloe** [comment]
> I'll back when I get something.

Okay, it's improved in meshio. A more memory-efficient and a little faster than the sdf-variant with `tofile()`. https://github.com/nschloe/meshio/pull/1033/files
