### ISSUE TITLE
example.py saves STL file, but it's empty

### ISSUE THREAD

**Issue by PavelSavkin** [fogleman/sdf#12]
UPDATE : I solved this issue by changing marching_cubes function to marching_cubes_lewiner function inside mesh.py.

Hi !
I have ran your examples (examples.example.py), which seemed to work well.
However, saved STL file was empty, with no information stored in it, as Meshlab didn't show anything.

Here's logs I've got
`(base) D:\Source\Research\sdf>python examples/example.py`
`min -0.84543, -0.84543, -0.84543`
`max 0.845431, 0.845431, 0.845431`
`step 0.0104847, 0.0104847, 0.0104847`
`4657463 samples in 216 batches with 16 workers`
 ` 100% (216 of 216) [##############################] 0:00:00 0:00:00`
`44 skipped, 172 empty, 0 nonempty`
`0 triangles in 0.442999 seconds`

It says I have 0 triangles...

Do you have any ideas why this is happening ?
Here's the output stl in case you want to check it.
[out.zip](https://github.com/fogleman/sdf/files/6056142/out.zip)

Additions :
I have also tried using .generate(), which gave me an empty list of points.
However, when I used .show_slice(), it actually visualized the result.
![image](https://user-images.githubusercontent.com/20761484/109405475-2f536200-79b4-11eb-8cae-f40522b58b74.png)

**Comment by fogleman** [comment]
Sounds like you may have been using an old version of scikit-image

**Comment by PavelSavkin** [comment]
Yeah after following to https://github.com/fogleman/sdf/issues/1 and upgrading it worked as well. 
Thank you !
