### ISSUE TITLE
Global install

### ISSUE THREAD

**Issue by nathanielvirgo** [fogleman/sdf#13]
This is a bit of a noob question, but is there a way to install this library instead of running in a virtualenv? After following the install instructions I can run the examples, but I can't work out how to import the library into code that's not located in the source folder.

(I know my way around Python pretty well, but I'm an academic rather than a developer and have never used virtualenv.)

**Comment by fogleman** [comment]
You can just do the `pip install -e .` step without activating a virtualenv first, and it should get installed globally.

**Comment by nathanielvirgo** [comment]
Cool, thanks that worked!
