### ISSUE TITLE
Unable to recreate displacement example

### ISSUE THREAD

**Issue by zumpchke** [fogleman/sdf#18]
I am unable to recreate the displacement example from
https://iquilezles.org/www/articles/distfunctions/distfunctions.htm

My attempt

```
diff --git a/sdf/d3.py b/sdf/d3.py
index 237c1cd..44829c5 100644
--- a/sdf/d3.py
+++ b/sdf/d3.py
@@ -500,6 +500,16 @@ def wrap_around(other, x0, x1, r=None, e=ease.linear):
         return other(q)
     return f
 
+@op3
+def displace(other):
+    def f(p):
+        x = p[:,0]
+        y = p[:,1]
+        z = p[:,2]
+        d2 = np.sin(20*x)*np.sin(20*y)*np.sin(20*z)
+        return other(p) + d2
+    return f
+
```

results in

```
 % python3 test.py
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    f.save('out.stl')
  File "/vanfiles/repos/sdf/sdf/d3.py", line 43, in save
    return mesh.save(path, self, *args, **kwargs)
  File "/vanfiles/repos/sdf/sdf/mesh.py", line 152, in save
    points = generate(*args, **kwargs)
  File "/vanfiles/repos/sdf/sdf/mesh.py", line 92, in generate
    bounds = _estimate_bounds(sdf)
  File "/vanfiles/repos/sdf/sdf/mesh.py", line 77, in _estimate_bounds
    volume = sdf(P).reshape((len(X), len(Y), len(Z)))
ValueError: cannot reshape array of size 16777216 into shape (16,16,16)
```

Any tips on getting this to work?

**Comment by zumpchke** [comment]
Tried calling it like
```f = torus(1, 0.25).displace()```

and 

```f = displace(torus(1, 0.25))```

**Comment by fogleman** [comment]
Try `other(p) + d2.reshape((-1, 1))`. The issue is the way numpy handles that addition based on the array "shapes".

Also you'll probably want a scaling factor on the amplitude.

**Comment by zumpchke** [comment]
Thanks! Any intuition for the scaling? With a factor of 1, it seems completely borked. 0.05 works good -- applied here to rounded box.

![image](https://user-images.githubusercontent.com/7519133/110576190-0b5e0080-81ac-11eb-9ca1-feef3d8a479d.png)

**Comment by fogleman** [comment]
Well, you're adding up three sine waves so your default amplitude is from -3 to 3, so that can be way too big for a small shape.
