### ISSUE TITLE
slab() is broken

### ISSUE THREAD

**Issue by pomeroyb** [fogleman/sdf#2]
To reproduce:
```python
from sdf import *
f = slab()
```
Output:
```Traceback (most recent call last):
  File "example.py", line 3, in <module>
    f = slab()
  File "C:\Users\Brandon\Documents\GitHub\sdf\sdf\d3.py", line 49, in wrapper
    return SDF3(f(*args, **kwargs))
  File "C:\Users\Brandon\Documents\GitHub\sdf\sdf\d3.py", line 133, in slab
    return intersection(*fs, k=k)
  File "C:\Users\Brandon\Documents\GitHub\sdf\sdf\d3.py", line 54, in wrapper
    return SDF3(f(*args, **kwargs))
TypeError: intersection() missing 1 required positional argument: 'a'```

**Comment by fogleman** [comment]
`slab` isn't intended to be used alone. It extends out to infinity on any undefined planes. It's meant to be intersected with other shapes to cut them, e.g.

    sphere(1) & slab(z0 = -0.2, z1 = 0.2)

**Comment by pomeroyb** [comment]
👍

**Comment by fogleman** [comment]
That function could use a better name, perhaps. Open to suggestions.

**Comment by fogleman** [comment]
In fact, maybe it shouldn't be defined like a primitive at all. And instead be like an "operator" that functions on another SDF:

`sphere(1).cut(z0=-0.2, z1=0.2)`

**Comment by pomeroyb** [comment]
There are a couple primitives that act like that (Plane and non-capped Cylinder). I've been differentiating them by referring to them as "non-meshable" in the comments:
https://github.com/pomeroyb/sdf/blob/main/sdf/d3.py#L119

But hiding the pseudo-primitives behind a function will probably be easier for new users to understand.
Something like `sphere(1).hole(radius=0.25)` for a cylinder and `sphere(1).section((1,1,0)` for a plane.
