### ISSUE TITLE
Problem with a large number of SDF while meshing

### ISSUE THREAD

**Issue by cpop-fr** [fogleman/sdf#40]
Hello,

I tried to work on a large number of SDF like:

```
sys.setrecursionlimit(1000000000)

f = capped_cylinder(0, 10*Z, 1) 

bound_max=10000
for i in range(1,10000):
    f = f | capped_cylinder(-Z, Z, 1).translate((i*0.1, 0, 0))

try:
    f.save('performance.stl', bounds=((0, 0, 0), (bound_max*0.1, 1, 1)))
except:
    print('export error')
```

I didn't catch any error but the script do not work. It appears that there is a silent error with the line 

`volume = sdf(P).reshape((len(X), len(Y), len(Z)))`

More precisely, it's the sdf(P) function that didn't work.

This is why I add 'bounds' parameter in the save function to skip the call of the volume line.
Unfortunately this line is call again in the __worker_ function.

Did anyone know where is the problem with the sdf(P) call?

For your information I tried with different range. Until 1000 it's works fine.

**Comment by nobodyinperson** [comment]
You effectively creat a nested function with 10000*10000 nesting levels. That is indeed a weak point in sdf that every operation introduces a nested function call.

In your case I'd use `union(bla,bli,blubb...)` or `union(*[make my sdfs])`, that could help.
