### ISSUE TITLE
How does batching work?

### ISSUE THREAD

**Issue by Korijn** [fogleman/sdf#6]
Cool library! I was just reading your code and noticed you call marching_cubes on subsections of the SDF, but I don't see any "stitching" code when you put the subsections back together. Doesn't that lead to lots of extra triangles on the inside of the mesh on the subsection boundaries? Just wondering if you could explain how this works :)

**Comment by LeLocTai** [comment]
I assume triangles are only generated on the surface of the mesh - where the distance function eval to 0

**Comment by Korijn** [comment]
Right, of course, how did I not think of that :) thanks!

**Comment by Korijn** [comment]
Let's say I could still imagine this happening in this case that boundaries coincidence with the surface; but I guess that can be avoided somehow with the batching strategy.. although there are probably some nasty edge cases.
